### ISSUE TITLE
[ADD APP] Yahtzee

### ISSUE THREAD

**Issue by hkalbasi** [foss-pwa/app-list#1]
## Schema

```yaml
id: yahtzee
source:
  type: github
  repository: zpix1/yahtzee
category:
  - game
lang:
  en:
    manifest: https://zpix1.github.io/yahtzee/static/manifest.json
```
